//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carwings.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Carwings.Test.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;status&quot;:200,&quot;userId&quot;:&quot;&lt;userid&gt;&quot;,&quot;vin&quot;:&quot;&lt;vin&gt;&quot;,&quot;resultKey&quot;:&quot;6vh9J5i5Ae14eCO92heRjYfEOafUFirm3zMnUUJ5YkZcNNCqUG&quot;}.
        /// </summary>
        internal static string BeginGetBatteryStatusResponse {
            get {
                return ResourceManager.GetString("BeginGetBatteryStatusResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;status&quot;:200,&quot;responseFlag&quot;:&quot;1&quot;,&quot;operationResult&quot;:&quot;START&quot;,&quot;timeStamp&quot;:&quot;2019-12-03 16:16:38&quot;,&quot;cruisingRangeAcOn&quot;:&quot;111760.0&quot;,&quot;cruisingRangeAcOff&quot;:&quot;144272.0&quot;,&quot;currentChargeLevel&quot;:&quot;0&quot;,&quot;chargeMode&quot;:&quot;NOT_CHARGING&quot;,&quot;pluginState&quot;:&quot;CONNECTED&quot;,&quot;charging&quot;:&quot;NO&quot;,&quot;chargeStatus&quot;:&quot;CT&quot;,&quot;batteryDegradation&quot;:&quot;12&quot;,&quot;batteryCapacity&quot;:&quot;12&quot;,&quot;timeRequiredToFull&quot;:{&quot;hours&quot;:&quot;&quot;,&quot;minutes&quot;:&quot;&quot;},&quot;timeRequiredToFull200&quot;:{&quot;hours&quot;:&quot;&quot;,&quot;minutes&quot;:&quot;&quot;},&quot;timeRequiredToFull200_6kW&quot;:{&quot;hours&quot;:&quot;&quot;,&quot;minutes&quot;:&quot;&quot;}}.
        /// </summary>
        internal static string EndGetBatteryStatusResponse {
            get {
                return ResourceManager.GetString("EndGetBatteryStatusResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;status&quot;:200,&quot;BatteryStatusRecords&quot;:{&quot;OperationResult&quot;:&quot;START&quot;,&quot;OperationDateAndTime&quot;:&quot;2019\/12\/03 16:16&quot;,&quot;BatteryStatus&quot;:{&quot;BatteryChargingStatus&quot;:&quot;NOT_CHARGING&quot;,&quot;BatteryCapacity&quot;:&quot;12&quot;,&quot;BatteryRemainingAmount&quot;:&quot;12&quot;,&quot;BatteryRemainingAmountWH&quot;:&quot;&quot;,&quot;BatteryRemainingAmountkWH&quot;:&quot;&quot;},&quot;PluginState&quot;:&quot;CONNECTED&quot;,&quot;CruisingRangeAcOn&quot;:&quot;111760.0&quot;,&quot;CruisingRangeAcOff&quot;:&quot;144272.0&quot;,&quot;NotificationDateAndTime&quot;:&quot;2019\/12\/03 16:16&quot;,&quot;TargetDate&quot;:&quot;2019\/12\/03 16:16&quot;}}.
        /// </summary>
        internal static string GetLastBatteryStatusResponse {
            get {
                return ResourceManager.GetString("GetLastBatteryStatusResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;status&quot;:200,&quot;message&quot;:&quot;success&quot;,&quot;baseprm&quot;:&quot;88dSp7wWnV3bvv9Z88zEwg&quot;}.
        /// </summary>
        internal static string InitializeResponse {
            get {
                return ResourceManager.GetString("InitializeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;status&quot;:200,&quot;vehicleInfo&quot;:[{&quot;vin&quot;:&quot;&lt;vin&gt;&quot;,&quot;nickname&quot;:&quot;&lt;nickname&gt;&quot;,&quot;charger20066&quot;:&quot;false&quot;,&quot;telematicsEnabled&quot;:&quot;true&quot;,&quot;custom_sessionid&quot;:&quot;&lt;custom-session-id&gt;&quot;}],&quot;vehicle&quot;:{&quot;profile&quot;:{&quot;vin&quot;:&quot;&lt;vin&gt;&quot;,&quot;gdcUserId&quot;:&quot;&quot;,&quot;gdcPassword&quot;:&quot;&quot;,&quot;encAuthToken&quot;:&quot;695C7B5D3DF7C89DF4FC33DD8C0698E24A112FB7D6E3BCA96200DA67F3D52E81&quot;,&quot;dcmId&quot;:&quot;201399042813&quot;,&quot;status&quot;:&quot;true&quot;,&quot;statusDate&quot;:&quot;2019\/07\/09 22:00&quot;,&quot;nickname&quot;:&quot;&lt;nickname&gt;&quot;}},&quot;EncAuthToken&quot;:&quot;183A765957CEB530788B60C8737A24B8ABB2D6A833A5A170125C6E630FC7451CAC06E100B1EB2439&quot;,&quot;Cus [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoginResponse {
            get {
                return ResourceManager.GetString("LoginResponse", resourceCulture);
            }
        }
    }
}
